[package]
name = "lookinggla-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ligmars = "0.1.1"
shared_memory = "0.12.4"
thiserror = "1.0.50"

[build-dependencies]
bindgen = "^0.68"
